export const SET_CONNECTION_STATUS = "SET_CONNECTION_STATUS";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_MESSAGE_SHOWN = "SET_MESSAGE_SHOWN";
export const SET_DEVICE_LOCALE = "SET_DEVICE_LOCALE";
export const SET_BROWSER_STATUS = "SET_BROWSER_STATUS";
export const SET_LOADING = "SET_LOADING";

export default {
  LOADING: "LOADING",
  BROWSER_STATUS_UPDATE: "BROWSER_STATUS_UPDATE",
  SET_LOCALE: "SAVE_LOCALE",
  SET_CONNECTION_STATUS: "SAVE_CONNECTION_STATUS",
  SET_MESSAGE_SHOW: "SAVE_MESSAGE_SHOW",
  SET_LOGIN_STATUS: "SAVE_LOGIN_STATUS"
};
