export default {
  HomeStack: 'HomeStack',
  PaymentsStack: 'PaymentsStack',
  AuthStack: 'Auth',
  MainNavigator: 'Main',
  PinPad: 'PinPadMain',
  AgreementAuth: 'AgreementAuth',
  PhoneAuth: 'PhoneAuth',
  PinPadAuth: 'PinPad',
  AgreementSelection: 'AgreementSelection',
  Home: 'Home',
  Payments: 'Payments',
  AutoPayment: 'Auto',
  PaymentsHistory: 'PaymentsHistory',
  PaymentService: 'PaymentService',
  DirectInfo: 'DirectInfo',
  VoipInfo: 'VoipInfo',
  IptvInfo: 'IptvInfo',
  Messages: 'Messages',
}
