export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
export const GET_AUTOPAYMENT_INFO = "GET_AUTOPAYMENT_INFO";
export const GET_PAYMENT_HISTORY = "GET_PAYMENT_HISTORY";
export const SET_AUTOPAYMENT_SETTINGS = "SET_AUTOPAYMENT_SETTINGS";
export const REMOVE_CARD = "REMOVE_CARD";
export const PAY = "PAY";
export const ACTIVATE_PAY_CARD = "ACTIVATE_PAY_CARD";

export default {
  SAVE_PAYMENT_TYPES: "SAVE_PAYMENT_TYPES",
  SAVE_AUTOPAYMENT_STATUS: "SAVE_AUTOPAYMENT_STATUS",
  SAVE_AUTOPAYMENT_LIMIT: "SAVE_AUTOPAYMENT_LIMIT",
  SAVE_CARDS: "SAVE_CARDS",
  SAVE_CARD_ID: "SAVE_CARD_ID",
  SAVE_PAYMENT_HISTORY: "SAVE_PAYMENT_HISTORY",
  CLEAR_PAYMENTS_INFO: "CLEAR_PAYMENTS_INFO",
  SAVE_PAYMENT_SERVICE_URL: "SAVE_PAYMENT_SERVICE_URL"
};
