export const AUTHENTICATE = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_PIN = "SET_PIN";
export const UNSET_PIN = "UNSET_PIN";
export const SET_USE_PIN = "SET_USE_PIN";
export const SET_USE_BIOMETRY = "SET_USE_BIOMETRY";
export const SET_PIN_LENGTH = "SET_PIN_LENGTH";
export const RESET_PIN_SETTINGS = "RESET_PIN_SETTINGS";
export const SMS_CODE = "SMS_CODE";
export const RESET_SMS = "RESET_SMS";
export const SMS_TIMEOUT = "SMS_TIMEOUT";

export default {
  SAVE_TOKEN: "SAVE_TOKEN",
  REMOVE_TOKEN: "REMOVE_TOKEN",
  SAVE_PIN: "SAVE_PIN",
  REMOVE_PIN: "REMOVE_PIN",
  SAVE_USE_PIN: "SAVE_USE_PIN",
  RESET_USE_PIN: "RESET_USE_PIN",
  SAVE_USE_BIOMETRY: "SAVE_USE_BIOMETRY",
  RESET_USE_BIOMETRY: "RESET_USE_BIOMETRY",
  SAVE_PIN_LENGTH: "SAVE_PIN_LENGTH",
  RESET_PIN_LENGTH: "RESET_PIN_LENGTH",
  SET_SMS_TIMEOUT: "SET_SMS_TIMEOUT",
  CODE_SENT: "CODE_SENT",
  RESET_CODE: "RESET_CODE"
};
