export const GET_BALANCE = "GET_BALANCE";
export const GET_AGREEMENT_LIST = "GET_AGREEMENT_LIST";
export const SET_AGREEMENT = "SET_AGREEMENT";
export const REMOVE_AGREEMENT = "REMOVE_AGREEMENT";
export const GET_INFO = "GET_INFO";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const CLEAR_AGREEMENT = "CLEAR_AGREEMENT";

export default {
  SAVE_BALANCE: "SAVE_BALANCE",
  SAVE_AGREEMENT_LIST: "SAVE_AGREEMENT_LIST",
  SAVE_AGREEMENT_INFO: "SAVE_AGREEMENT_INFO",
  SAVE_CURRENT_AGREEMENT: "SAVE_CURRENT_AGREEMENT",
  REMOVE_CURRENT_AGREEMENT: "REMOVE_CURRENT_AGREEMENT",
  CLEAR_ALL_DATA: "CLEAR_ALL_DATA",
  CLEAR_AGREEMENT_DATA: "CLEAR_AGREEMENT_DATA"
};
